baseURL = 'https://marinyacc.github.io/' 
languageCode = 'zh-cn'
title = "Marinyacc | Weblog" # 建议加上一句话描述
theme = "simple-frame" 

# 网站描述，有利于搜索引擎(SEO)抓取
description = "一份记录计算机技术与生活的博客。"

[permalinks]
  search = "/search/"

# 导航菜单
[[menu.main]]
    name = "首页"
    url = "/posts/"
    weight = 1
[[menu.main]]
    name = "杂谈"
    url = "/docs/"
    weight = 2

[Params]
  # 评论开关
  enableComments = true
  
  # 如果使用不蒜子浏览量
  enableBusuanzi = true
  
  Subtitle = "QQ: 2157489466| 28届南邮本科"
#   mainSections = ["posts"]
  post_meta = ["date", "taglist"]
  dateformat = "2006-01-02"
  
  # 功能增强
  pager = true          # 开启上一篇/下一篇翻页
  
  # 版权声明 (显示在页面底部)
  copyright = " powered by hugo. 转载请标明出处"

# 侧边栏配置
[Params.sidebar]
  home = "right"
  list = "right"
  single = "right"
  widgets = ["search", "taglist", "recent", "archives"]

[Params.widgets]
  recent_num = 5
  tags_counter = true

[taxonomies]
  tag = "tags"
  archive = "archives"

[related]
  includeNewer = true
[[related.indices]]
  name = "tags"
  weight = 80

